// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvvDo2KNNzjTBs7KpYKxy8dtONO8Z0ftQ',
    appId: '1:583106009232:web:8fa55886172ee08aba6015',
    messagingSenderId: '583106009232',
    projectId: 'programming-419909',
    authDomain: 'programming-419909.firebaseapp.com',
    databaseURL: 'https://programming-419909-default-rtdb.firebaseio.com',
    storageBucket: 'programming-419909.appspot.com',
    measurementId: 'G-TEF45G25E6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlrcO6w0cx2c_mwDObPXbUfTJAQLyZZLI',
    appId: '1:583106009232:android:e82b7727c488e4daba6015',
    messagingSenderId: '583106009232',
    projectId: 'programming-419909',
    databaseURL: 'https://programming-419909-default-rtdb.firebaseio.com',
    storageBucket: 'programming-419909.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjxyYJ-1Jf586FjFCzx6A0al6foxk0UqA',
    appId: '1:583106009232:ios:efaca080879e6bd4ba6015',
    messagingSenderId: '583106009232',
    projectId: 'programming-419909',
    databaseURL: 'https://programming-419909-default-rtdb.firebaseio.com',
    storageBucket: 'programming-419909.appspot.com',
    iosBundleId: 'com.example.shimohuriTopic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjxyYJ-1Jf586FjFCzx6A0al6foxk0UqA',
    appId: '1:583106009232:ios:efaca080879e6bd4ba6015',
    messagingSenderId: '583106009232',
    projectId: 'programming-419909',
    databaseURL: 'https://programming-419909-default-rtdb.firebaseio.com',
    storageBucket: 'programming-419909.appspot.com',
    iosBundleId: 'com.example.shimohuriTopic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvvDo2KNNzjTBs7KpYKxy8dtONO8Z0ftQ',
    appId: '1:583106009232:web:e47f9b47b3e47cdfba6015',
    messagingSenderId: '583106009232',
    projectId: 'programming-419909',
    authDomain: 'programming-419909.firebaseapp.com',
    databaseURL: 'https://programming-419909-default-rtdb.firebaseio.com',
    storageBucket: 'programming-419909.appspot.com',
    measurementId: 'G-WRZ4GZL4G2',
  );
}
